### ISSUE TITLE
Crash when trying to open URL

### ISSUE THREAD

**Issue by Garanas** [FAForever/FADeepProbe#1]
The debugger crashes (and takes the game with it) when you try and open a URL in-game. An example is in the lobby, where you have a URL to Github when looking at the patches.

![image](https://user-images.githubusercontent.com/15778155/151504840-40fcc1a1-5673-4748-abab-f1f836033640.png)

Error message related to the crash:

![image](https://user-images.githubusercontent.com/15778155/151504952-ad3a6695-95a7-40ab-97a2-fb82b3d89e07.png)

**Comment by KionX** [comment]
I've already fixed it. Has it not improved?

**Comment by Garanas** [comment]
You are correct - I must have tested on an older version. The version the client distributes works fine.
